services:
  - type: web
    name: telegram-card-counter-bot
    env: python
    runtime: python-3.11.10
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DISPLAY_CHANNEL
        sync: false
